export const DEFAULT_SWIPE_DISMISS_THRESHOLD = 40;
export const DEFAULT_SWIPE_DISMISS_AXIS_THRESHOLD = 8;
export const DEFAULT_SWIPE_DISMISS_SNAP_BACK_DURATION_MS = 180;
export const DEFAULT_SWIPE_DISMISS_SWIPE_VELOCITY = 0.2;
export const DEFAULT_SWIPE_DISMISS_SWIPE_DURATION_MS = 400;
